#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# gen_keys.sh: generate the Lumen OS release keys on the Mac (owner only, run once).
#
#   bash gen_keys.sh [KEYS_DIR]          default KEYS_DIR = ~/.lumen-keys
#
# Writes, for every name below:  <name>.pk8 (unencrypted PKCS#8 DER private key, mode 600),
# <name>.x509.pem (public certificate), and FINGERPRINTS.txt (SHA-256 of each certificate).
# The private keys have NO password (owner decision 2026-10-06); protection is the directory
# itself: ~/.lumen-keys, mode 700, on the Mac only. Never copy this directory into the project
# tree, the build laptop, a git repository or a cloud folder. Make two offline backups
# (see docs/keys.md).
#
# Refuses to overwrite an existing key: losing or replacing 'platform' means every install
# must be reflashed with a data wipe; losing 'ota' means no more OTA updates.
#
# Keys (AOSP names, so the usual tools find them):
#   platform shared media networkstack sdk_sandbox bluetooth nfc releasekey   RSA-2048, e=65537
#   ota ota_next                                                              RSA-4096, e=65537
# 'releasekey' replaces AOSP 'testkey'. 'ota' signs payloads + update manifests; 'ota_next'
# is a spare certificate pre-installed in otacerts.zip for one future key rotation.
# Subject: /O=Lumen OS/OU=kmuradoff/CN=Lumen OS <name>  (no e-mail, no country: certs are public)
set -euo pipefail

KD=${1:-$HOME/.lumen-keys}
DAYS=${DAYS:-10000}
RSA2048="platform shared media networkstack sdk_sandbox bluetooth nfc releasekey"
RSA4096="ota ota_next"
OPENSSL=${OPENSSL:-$(command -v openssl)}

die() { echo "gen_keys: $*" >&2; exit 1; }

case $KD in
  *"XGIMI PLAY 6"*|*/gsi/*|*/gsi) die "refusing to create keys inside the project tree: $KD" ;;
esac
[ -n "$OPENSSL" ] || die "no openssl"
umask 077
mkdir -p "$KD"
chmod 700 "$KD"

gen() {  # name bits
  local n=$1 bits=$2 tmp
  if [ -e "$KD/$n.pk8" ] || [ -e "$KD/$n.x509.pem" ]; then
    echo "keep existing $n"; return 0
  fi
  tmp=$(mktemp -d "$KD/.tmp.XXXXXX")
  "$OPENSSL" genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:"$bits" -pkeyopt rsa_keygen_pubexp:65537 \
    -out "$tmp/key.pem" 2>/dev/null
  "$OPENSSL" req -new -x509 -sha256 -key "$tmp/key.pem" -days "$DAYS" \
    -subj "/O=Lumen OS/OU=kmuradoff/CN=Lumen OS $n" -out "$tmp/cert.pem"
  "$OPENSSL" pkcs8 -in "$tmp/key.pem" -topk8 -outform DER -nocrypt -out "$tmp/key.pk8"
  mv "$tmp/key.pk8" "$KD/$n.pk8"
  mv "$tmp/cert.pem" "$KD/$n.x509.pem"
  rm -rf "$tmp"
  chmod 600 "$KD/$n.pk8"; chmod 644 "$KD/$n.x509.pem"
  echo "generated $n (RSA-$bits)"
}

for n in $RSA2048; do gen "$n" 2048; done
for n in $RSA4096; do gen "$n" 4096; done

# sanity: every pk8 matches its certificate
for n in $RSA2048 $RSA4096; do
  a=$("$OPENSSL" pkey -inform DER -in "$KD/$n.pk8" -pubout -outform DER | shasum -a 256 | cut -d' ' -f1)
  b=$("$OPENSSL" x509 -in "$KD/$n.x509.pem" -pubkey -noout | "$OPENSSL" pkey -pubin -outform DER | shasum -a 256 | cut -d' ' -f1)
  [ "$a" = "$b" ] || die "$n.pk8 does not match $n.x509.pem"
done

{
  echo "# Lumen OS release certificates (public). SHA-256 of the DER certificate."
  for n in $RSA2048 $RSA4096; do
    printf '%-13s %s\n' "$n" "$("$OPENSSL" x509 -in "$KD/$n.x509.pem" -outform DER | shasum -a 256 | cut -d' ' -f1)"
  done
} > "$KD/FINGERPRINTS.txt"
chmod 644 "$KD/FINGERPRINTS.txt"
cat > "$KD/README.txt" <<'EOF'
Lumen OS release keys (owner: kmuradoff). NO PASSWORDS: whoever has this folder can sign
system updates for every Lumen OS projector. Keep it only on this Mac (mode 700) plus two
offline backups (e.g. an encrypted USB stick and a password-manager attachment).
Never copy it into the project tree, the build laptop, git, iCloud/Dropbox, or a chat.
Generated by gsi/tools/sign/gen_keys.sh; used by gsi/tools/sign/sign_tar.py and gsi/tools/ota/*.
EOF
chmod 644 "$KD/README.txt"
echo "keys in $KD:"
cat "$KD/FINGERPRINTS.txt"
