#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""gen_lineage_rro.py: generate gsi/apps/Z9xLineagePlatformOverlay (static RRO on lineageos.platform,
plan C8: the speed and brand RROs merged into one) from the target APK of the base image.

  gen_lineage_rro.py AAPT2 org.lineageos.platform-res.apk APP_DIR

Values:
  integer/config_doubleTapOnHomeBehavior = 0   (Lineage TV overlay: 2 = APP_SWITCH, a no-op on TV that
      makes PhoneWindowManager defer EVERY short HOME press by the 300 ms double-tap timeout)
  integer/config_longPressOnHomeBehavior = 3   (SEARCH = launch assist with invocation_type 5: Recent
      apps in org.z9x.projector; the Lineage default, written out so nobody changes it)
  string/lineage_version, lineageos_system_label, lineage_updates: the target's own text with
      "LineageOS" replaced by "Lumen OS", for EVERY configuration the target defines. RRO lookup is
      per configuration: an overlay with only values/ would leave e.g. "Версия LineageOS" in a Russian
      UI. The target's translations stay, only the brand changes ("Версия Lumen OS"), so no new
      translatable text is introduced (nothing for i18n/gen.py). Pseudo-locales (en-rXA, ar-rXB) skipped.
About > "Lumen OS version" then shows ro.lineage.display.version = "1.0 (kmuradoff)" (lumen_v1.sh).
The target declares no <overlayable>, so a preinstalled product overlay is accepted (same as the
TvSettings HDR RRO).
"""
import os
import re
import shutil
import subprocess
import sys
from xml.sax.saxutils import escape

STRINGS = ['lineage_version', 'lineageos_system_label', 'lineage_updates']
INTEGERS = {'config_doubleTapOnHomeBehavior': 0, 'config_longPressOnHomeBehavior': 3}
BRAND_OLD, BRAND_NEW = 'LineageOS', 'Lumen OS'

MANIFEST = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Lumen OS 1.0: static RRO on lineageos.platform (/system/framework/org.lineageos.platform-res.apk),
     installed as /system/product/overlay/Z9xLineagePlatformOverlay.apk, priority 2000 (above Lineage's
     auto-generated product RRO, priority 1). Plan C8 merges the speed RRO (HOME double-tap 0) and the
     brand RRO (About strings) into this one package. GENERATED by gsi/tools/lumen/gen_lineage_rro.py
     from the base image's target APK: edit the generator, not the res/ files.
     No code, no permissions. Signed with the release platform key by the sign stage. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.z9x.overlay.lineageplatform"
    android:versionCode="102"
    android:versionName="1.0.1">
    <overlay
        android:targetPackage="lineageos.platform"
        android:isStatic="true"
        android:priority="2000" />
    <application android:hasCode="false" />
</manifest>
'''


def dir_for(cfg):
    """aapt2 dump config ('ru', 'pt-rBR', 'ast-rES') -> values dir name; None = skip."""
    if cfg == '':
        return 'values'
    if 'rXA' in cfg or 'rXB' in cfg or '-' in cfg.replace('-r', '', 1):
        return None                      # pseudo-locales and grammatical-gender variants
    lang, _, reg = cfg.partition('-r')
    if not re.fullmatch(r'[a-z]{2,3}', lang) or (reg and not re.fullmatch(r'[A-Z]{2}|[0-9]{3}', reg)):
        return None
    if len(lang) == 3:
        return 'values-b+%s%s' % (lang, ('+' + reg) if reg else '')
    return 'values-%s%s' % (lang, ('-r' + reg) if reg else '')


def parse_dump(text):
    """{name: {cfg: value}} for the strings we override, {name: value} for integers."""
    strings, ints, cur = {}, {}, None
    for line in text.splitlines():
        m = re.match(r'\s+resource 0x[0-9a-f]+ (string|integer)/(\S+)', line)
        if m:
            cur = (m.group(1), m.group(2)) if m.group(2) in STRINGS or m.group(2) in INTEGERS else None
            continue
        if cur is None:
            continue
        m = re.match(r'\s+\(([^)]*)\) (.*)$', line)
        if not m:
            if re.match(r'\s+(resource|type) ', line):
                cur = None
            continue
        cfg, val = m.group(1), m.group(2)
        if cur[0] == 'string':
            if not (val.startswith('"') and val.endswith('"')):
                sys.exit('unexpected value for %s (%s): %r' % (cur[1], cfg, val))
            strings.setdefault(cur[1], {})[cfg] = val[1:-1].replace('\\"', '"').replace("\\'", "'")
        else:
            ints[cur[1]] = val
    return strings, ints


def android_escape(s):
    s = escape(s)
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"').replace('@', '\\@', 1 if s.startswith('@') else 0)


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    aapt2, target, app = sys.argv[1:]
    dump = subprocess.run([aapt2, 'dump', 'resources', target], check=True, capture_output=True, text=True).stdout
    strings, ints = parse_dump(dump)
    for n in STRINGS:
        if n not in strings or '' not in strings[n]:
            sys.exit('target has no default string/%s' % n)
    for n in INTEGERS:
        if n not in ints:
            sys.exit('target has no integer/%s' % n)
    res = os.path.join(app, 'res')
    if os.path.isdir(res):
        shutil.rmtree(res)
    os.makedirs(os.path.join(res, 'values'))
    with open(os.path.join(app, 'AndroidManifest.xml'), 'w') as f:
        f.write(MANIFEST)
    with open(os.path.join(res, 'values', 'config.xml'), 'w') as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n'
                '<!-- GENERATED by gsi/tools/lumen/gen_lineage_rro.py (see its docstring). Target values: %s -->\n'
                '<resources>\n' % ', '.join('%s=%s' % kv for kv in sorted(ints.items())))
        for n, v in sorted(INTEGERS.items()):
            f.write('    <integer name="%s">%d</integer>\n' % (n, v))
        f.write('</resources>\n')
    per_dir, skipped = {}, set()
    for n in STRINGS:
        for cfg, val in strings[n].items():
            d = dir_for(cfg)
            if d is None:
                skipped.add(cfg); continue
            if BRAND_OLD not in val:
                print('note: %s (%s) has no %r: %r -> "%s"' % (n, cfg, BRAND_OLD, val, BRAND_NEW))
                new = BRAND_NEW if n == 'lineage_version' else val
            else:
                new = val.replace(BRAND_OLD, BRAND_NEW)
            per_dir.setdefault(d, {})[n] = new
    for d, kv in sorted(per_dir.items()):
        os.makedirs(os.path.join(res, d), exist_ok=True)
        with open(os.path.join(res, d, 'strings.xml'), 'w', encoding='utf-8') as f:
            f.write('<?xml version="1.0" encoding="utf-8"?>\n<!-- GENERATED by gsi/tools/lumen/gen_lineage_rro.py -->\n<resources>\n')
            for n in STRINGS:
                if n in kv:
                    f.write('    <string name="%s">%s</string>\n' % (n, android_escape(kv[n])))
            f.write('</resources>\n')
    print('wrote %s: %d value dirs (skipped configs: %s)' % (app, len(per_dir) + 0, ', '.join(sorted(skipped)) or '-'))
    print('default: ' + ', '.join('%s="%s"' % (n, per_dir['values'][n]) for n in STRINGS))


if __name__ == '__main__':
    main()
