#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Lumen brand drawables: writes apps/common/brand/drawable/*.xml from lumen_brand.py.

  lumen_mark.xml            the mark "2A Aperture, facets" (viewport 200 = the board's -100..100 box)
  lumen_mark_mono.xml       one colour (white) for small sizes and notifications: the facets split
                            by slits, the hexagon cut out, no core (transparent)
  lumen_mark_small.xml      the board's 24 px variant: a disc with the hexagon cut out and a big core
  lumen_wordmark.xml        "lumen" as vector paths (own drawing, no font)
  brand_icon_<app>.xml      launcher icon: a #17181B rounded-square tile (board: 240 px, radius 58)
                            with the mark (Lumen Home) or the app glyph (the other apps)
  brand_banner_<app>.xml    320x180 dp TV banner on #17181B: the mark + "lumen" (Lumen Home),
                            the mark + the app glyph (the other apps: their names are localised and
                            a drawable cannot carry text)

Every file is a self-contained VectorDrawable (no @drawable reference), so an app can take any one
of them alone (apps/common/brand/sync.sh copies them).

Usage:  gen_drawables.py [--out DIR] [--preview DIR]
  --preview  also writes <name>.svg converted back FROM THE WRITTEN XML (an independent check of
             the pathData) and <name>.png rendered from it with ImageMagick, plus a contact sheet.
Requires: Python 3.8+; ImageMagick (magick) only for --preview.
"""
import argparse
import os
import subprocess
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.dont_write_bytecode = True
import lumen_brand as B  # noqa: E402

GSI = os.path.normpath(os.path.join(HERE, "..", ".."))
OUT_DEFAULT = os.path.join(GSI, "apps", "common", "brand", "drawable")
ANDROID = "http://schemas.android.com/apk/res/android"

MONO_GAP = 9.0          # slit width of the single-colour mark (viewport units of 200)
ICON_MARK = 164.0       # mark size on the 240 tile (board)
ICON_GLYPH = 132.0      # glyph size on the 240 tile
TILE_R = 58.0           # tile corner radius on 240 (board)
BANNER_MARK = 52.0      # mark box on the 320x180 banner (board)
BANNER_GAP = 14.0       # mark -> wordmark (board)
BANNER_XHEIGHT = 22.9   # "lumen" at 44 px (board): Onest x-height ~0.52 em
BANNER_GLYPH = 64.0     # glyph box on the sub-app banners
BANNER_SEP = 22.0       # mark -> divider -> glyph
DIVIDER = "#FF3A3631"   # hairline between the mark and the glyph (decoration only)

# app key -> (package, label used in the comment)
APPS = {
    "home": ("org.z9x.home", "Lumen Home (\"Lumen\")"),
    "projector": ("org.z9x.projector", "Projector"),
    "updater": ("org.z9x.updater", "Lumen OS update"),
    "airplay": ("org.z9x.airplay", "AirPlay"),
    "setup": ("org.z9x.setup", "Setup"),
    "tvinput": ("org.z9x.tvinput", "HDMI inputs"),
}


def argb(h, alpha=1.0):
    r, g, b = B.rgb(h)
    return "#%02X%02X%02X%02X" % (int(round(alpha * 255)), r, g, b)


def path_el(color, paths, fill_type="nonZero", name=None, indent="    "):
    d = " ".join(p.svg() for p in paths)
    attrs = []
    if name:
        attrs.append('android:name="%s"' % name)
    attrs.append('android:fillColor="%s"' % (color if color.startswith("#") and len(color) == 9
                                               else argb(color)))
    if fill_type != "nonZero":
        attrs.append('android:fillType="%s"' % fill_type)
    attrs.append('android:pathData="%s"' % d)
    return "%s<path %s />" % (indent, ("\n" + indent + "    ").join(attrs))


def vector(comment, w_dp, h_dp, vw, vh, body):
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            "<!-- SPDX-License-Identifier: Apache-2.0\n"
            "     %s\n"
            "     Generated by tools/brand/gen_drawables.py from tools/brand/lumen_brand.py: edit those and\n"
            "     re-run, do not edit this file. -->\n"
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="%sdp"\n    android:height="%sdp"\n'
            '    android:viewportWidth="%s"\n    android:viewportHeight="%s">\n%s\n</vector>\n'
            % (comment, B.fmt(w_dp), B.fmt(h_dp), B.fmt(vw), B.fmt(vh), "\n".join(body)))


# ------------------------------------------------------------------ pieces placed in a viewport

def mark_layers(cx, cy, size, core_r=B.CORE_R_SMALL):
    """The coloured mark with its -100..100 box scaled to `size` and centred on (cx, cy)."""
    s = size / 200.0
    fs = B.facets()
    a = [fs[i].xf(s, 0, cx, cy) for i in (0, 2, 4)]
    b = [fs[i].xf(s, 0, cx, cy) for i in (1, 3, 5)]
    return [(B.FACET_A, "nonZero", a), (B.FACET_B, "nonZero", b),
            (B.CORE, "nonZero", [B.circle(cx, cy, core_r * s)])]


def glyph_layers(key, cx, cy, size):
    s = size / 200.0
    return [(c, ft, [p.xf(s, 0, cx, cy) for p in ps]) for c, ft, ps in B.GLYPHS[key]()]


def wordmark_layer(x, y_top, xheight, color=B.FACET_A):
    shapes, box = B.wordmark()
    s = xheight / B.WM_X
    return (color, "nonZero", B.placed(shapes, box, s, x, y_top)), (box[2] - box[0]) * s, \
        (box[3] - box[1]) * s


def layers_xml(layers, indent="    "):
    return [path_el(c, ps, ft, indent=indent) for c, ft, ps in layers]


# ------------------------------------------------------------------ files

def f_mark():
    fs = B.facets()
    body = []
    for i, p in enumerate(fs):
        body.append(path_el(B.FACET_A if i % 2 == 0 else B.FACET_B, [p.xf(1, 0, 100, 100)],
                            name="facet%d" % i))
    body.append('    <group android:name="core" android:pivotX="100" android:pivotY="100">')
    body.append(path_el(B.CORE, [B.circle(100, 100, B.CORE_R)], name="core_light", indent="        "))
    body.append("    </group>")
    return vector("Lumen mark \"2A Aperture, facets\": six facets #F4EFE6 / #CFC7BA around a hexagonal\n"
                  "     opening with the warm core #F2B26B (viewport = the board's -100..100 box). Paths are named\n"
                  "     facet0..facet5 and core_light (group \"core\", pivot at the centre) for animated vectors.",
                  48, 48, 200, 200, body)


def f_mark_mono():
    fs = B.facets(gap=MONO_GAP)
    body = [path_el("#FFFFFFFF", [p.xf(1, 0, 100, 100) for p in fs])]
    return vector("Lumen mark, single colour (white, tint it): the six facets split by slits, the hexagon\n"
                  "     cut out, no core. For small sizes and notification icons.", 24, 24, 200, 200, body)


def f_mark_small():
    ring = [p.xf(1, 0, 100, 100) for p in B.facets()]          # union = disc minus the hexagon
    body = [path_el(B.FACET_A, ring), path_el(B.CORE, [B.circle(100, 100, 26)])]
    return vector("Lumen mark for 24..40 dp (board: the 24 px variant): a #F4EFE6 disc with the hexagonal\n"
                  "     opening cut out (it shows the background) and the warm core #F2B26B.",
                  24, 24, 200, 200, body)


def f_wordmark():
    pad = 4.0
    layer, w, h = wordmark_layer(pad, pad, 100.0)
    vw, vh = w + 2 * pad, h + 2 * pad
    body = layers_xml([layer])
    return vector("\"lumen\" wordmark #F4EFE6 as vector paths (own geometric drawing, no font): x-height 100,\n"
                  "     ascender 140 viewport units. Set its height; the width follows (%.3f : 1)." % (vw / vh),
                  round(16.0 * vw / vh, 2), 16, round(vw, 2), round(vh, 2), body)


def tile():
    return (B.TILE, "nonZero", [B.rrect(0, 0, 240, 240, TILE_R)])


def f_icon(key):
    pkg, label = APPS[key]
    if key == "home":
        layers = [tile()] + mark_layers(120, 120, ICON_MARK)
        what = "the mark"
    else:
        layers = [tile()] + glyph_layers(key, 120, 120, ICON_GLYPH)
        what = "the %s glyph" % key
    return vector("Launcher icon of %s (%s): %s on the #17181B rounded-square tile." % (label, pkg, what),
                  48, 48, 240, 240, layers_xml(layers))


def f_banner(key):
    pkg, label = APPS[key]
    bg = (B.TILE, "nonZero", [B.rect(0, 0, 320, 180)])
    if key == "home":
        shapes, box = B.wordmark()
        s = BANNER_XHEIGHT / B.WM_X
        ww, wh = (box[2] - box[0]) * s, B.WM_ASC * s
        total = BANNER_MARK + BANNER_GAP + ww
        x0 = (320.0 - total) / 2.0
        layers = [bg] + mark_layers(x0 + BANNER_MARK / 2.0, 90.0, BANNER_MARK)
        wm, _, _ = wordmark_layer(x0 + BANNER_MARK + BANNER_GAP, 90.0 - wh / 2.0, BANNER_XHEIGHT)
        layers.append(wm)
        what = "the mark and the \"lumen\" wordmark"
    else:
        total = BANNER_MARK + 2 * BANNER_SEP + BANNER_GLYPH
        x0 = (320.0 - total) / 2.0
        layers = [bg] + mark_layers(x0 + BANNER_MARK / 2.0, 90.0, BANNER_MARK)
        dx = x0 + BANNER_MARK + BANNER_SEP
        layers.append((DIVIDER, "nonZero", [B.rect(dx - 0.75, 90 - 22, dx + 0.75, 90 + 22)]))
        layers += glyph_layers(key, dx + BANNER_SEP + BANNER_GLYPH / 2.0, 90.0, BANNER_GLYPH)
        what = "the mark | the %s glyph" % key
    return vector("TV banner 320x180 dp of %s (%s): %s on #17181B, full bleed\n"
                  "     (launchers round the corners themselves)." % (label, pkg, what),
                  320, 180, 320, 180, layers_xml(layers))


def all_files():
    files = {
        "lumen_mark.xml": f_mark(),
        "lumen_mark_mono.xml": f_mark_mono(),
        "lumen_mark_small.xml": f_mark_small(),
        "lumen_wordmark.xml": f_wordmark(),
    }
    for k in APPS:
        files["brand_icon_%s.xml" % k] = f_icon(k)
        files["brand_banner_%s.xml" % k] = f_banner(k)
    return files


# ------------------------------------------------------------------ preview (XML -> SVG -> PNG)

def _a(el, name, default=None):
    return el.get("{%s}%s" % (ANDROID, name), default)


def vd_to_svg(xml_text, px_per_dp=2.0, bg=None):
    """Converts a VectorDrawable (vector / group / path subset used here) to SVG."""
    root = ET.fromstring(xml_text)
    w = float(_a(root, "width").replace("dp", "")) * px_per_dp
    h = float(_a(root, "height").replace("dp", "")) * px_per_dp
    vw, vh = float(_a(root, "viewportWidth")), float(_a(root, "viewportHeight"))

    def color(c):
        c = c.lstrip("#")
        if len(c) == 8:
            return "#" + c[2:], int(c[:2], 16) / 255.0
        return "#" + c, 1.0

    def walk(el):
        out = []
        for ch in el:
            tag = ch.tag
            if tag == "path":
                col, alpha = color(_a(ch, "fillColor", "#00000000"))
                alpha *= float(_a(ch, "fillAlpha", "1"))
                rule = "evenodd" if _a(ch, "fillType", "nonZero") == "evenOdd" else "nonzero"
                out.append('<path d="%s" fill="%s" fill-opacity="%.4f" fill-rule="%s"/>'
                           % (_a(ch, "pathData"), col, alpha, rule))
            elif tag == "group":
                px, py = float(_a(ch, "pivotX", "0")), float(_a(ch, "pivotY", "0"))
                tx, ty = float(_a(ch, "translateX", "0")), float(_a(ch, "translateY", "0"))
                sx, sy = float(_a(ch, "scaleX", "1")), float(_a(ch, "scaleY", "1"))
                rot = float(_a(ch, "rotation", "0"))
                t = "translate(%g %g) rotate(%g) scale(%g %g) translate(%g %g)" % (
                    tx + px, ty + py, rot, sx, sy, -px, -py)
                out.append('<g transform="%s">%s</g>' % (t, "".join(walk(ch))))
        return out
    back = '<rect width="%g" height="%g" fill="%s"/>' % (vw, vh, bg) if bg else ""
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="%g" height="%g" viewBox="0 0 %g %g">%s%s</svg>'
            % (w, h, vw, vh, back, "".join(walk(root))))


def preview(files, pdir):
    os.makedirs(pdir, exist_ok=True)
    pngs = []
    for name, xml in files.items():
        base = os.path.join(pdir, name[:-4])
        # light names on a dark ground, the mono mark on mid grey so its white shows
        bg = "#0A0908" if not name.startswith("lumen_mark_mono") else "#555555"
        for scale, suffix in ((2.0, ""), (8.0 if name.startswith(("lumen_mark", "brand_icon")) else 2.0, "_big")):
            svg = vd_to_svg(xml, scale, bg)
            with open(base + suffix + ".svg", "w") as f:
                f.write(svg)
            subprocess.run(["magick", "-background", "none", base + suffix + ".svg", base + suffix + ".png"],
                           check=True)
        pngs.append(base + ".png")
    # montage may warn about a missing label font and exit 1 although the sheet is written
    sheet = os.path.join(pdir, "contact_sheet.png")
    subprocess.run(["magick", "montage"] + sorted(pngs) + ["-tile", "6x", "-geometry", "+12+12",
                    "-background", "#2A2A2A", sheet], stderr=subprocess.DEVNULL)
    print("preview: %s (%d drawables)" % (pdir, len(pngs)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=OUT_DEFAULT)
    ap.add_argument("--preview", default=None)
    args = ap.parse_args()
    files = all_files()
    os.makedirs(args.out, exist_ok=True)
    for name, xml in files.items():
        ET.fromstring(xml)                      # well-formed
        with open(os.path.join(args.out, name), "w") as f:
            f.write(xml)
        print("wrote %-28s %6d bytes" % (name, len(xml.encode())))
    if args.preview:
        preview(files, args.preview)


if __name__ == "__main__":
    main()
