# SPDX-License-Identifier: Apache-2.0
# Lumen OS installer: properties of the image this installer ships with.
# BLOBS=partition (published default) a PUBLIC image: the codec files come from the user's own
#                 projector ('blobs' step) into the z9x_blobs_<slot> partition.
# The owner's PRIVATE image carries the MediaTek codec files itself: pass --blobs=embedded
# (-Blobs embedded on Windows). --no-blobs (-NoBlobs): a public image installed without the codec files
# (protected video will not work). BLOBS in the environment or on the command line wins over this file.
# The installer refuses a mismatch it can see: a -PRIVATE- image name,
# or with dump.erofs installed the codec placeholder size inside the image (0 bytes = public).
BLOBS=partition
VERSION=1.0
